/*					Código realizado durante el trabajo de tesis
 *	Arquitectura de Software Flexible y Genérica para Métodos del Tipo Newton
 *
 *										por 
 *			   				   Ricardo Serrato Barrera
 *
 *								     Asesores:
 *			  			     Dr. Gustavo Rodríguez Gómez
 *			 		         Dr. Saúl Pomares Hernández
 *			
 *			     				 1ro de diciembre 2011
 *
 *						Programador: Ricardo Serrato Barrera
 * 	
 */

package vistas;

import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**Esta es una pequeña ventana que permite escribir el punto de inicio o seleccionarlo
 * desde un archivo
 *
 * @author Ricardo
 */
@SuppressWarnings("serial")
public class PuntoInicio extends javax.swing.JDialog {

    /** Creates new form PuntoInicio */
    private int numeroVariables;
    private Controlador controlador;
    /** Creates new form PuntoInicio */
    public PuntoInicio(java.awt.Frame parent, boolean modal, int numeroVariables, Controlador controlador) {
        super(parent, modal);
        this.numeroVariables=numeroVariables;
        this.controlador=controlador;
        initComponents();
        setSize(100,300);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setModel(getModeloTabla());
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int i=tabla.getRowCount();
        int j=tabla.getColumnCount();
        double d[][]=new double[i][j];

        for(int x=0;x<i;x++)
        	for(int y=0;y<j;y++)
        	{
        		d[x][y]=Double.parseDouble(tabla.getValueAt(x, y).toString());
        	}

        controlador.setPuntoInicio(d);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:



    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        JFileChooser archivo = new JFileChooser();

			int retorno = archivo.showOpenDialog(this);

			if(JFileChooser.APPROVE_OPTION == retorno)
			{
				File file = archivo.getSelectedFile();

				try
				{
                                      Scanner scanner = new Scanner(file);
                                      Double d[][]=new Double[numeroVariables][1];
                                      int i=0;
                                      while(scanner.hasNext())
                                      {
                                         d[i][0]=Double.parseDouble(scanner.nextLine());
                                         i++;
                                      }

                                      tabla.setModel(new DefaultTableModel(d,new String[]{"X"}));


				}
				catch(Exception e)
				{
					System.out.println("No se encontro el archivo");
				}
			}
    }//GEN-LAST:event_jMenuItem1ActionPerformed


private TableModel getModeloTabla()
{
    Double d[][]=new Double[numeroVariables][1];

    for(int i=0;i<numeroVariables;i++)
      d[i][0]=(i+1)/10.0;/*

    d[0][0]=0.834;
    d[1][0]=0.8416;
    d[2][0]=0.951;
    d[3][0]=0.9534;
    d[4][0]=0.9645;
    d[5][0]= 0.9659;
    d[6][0]=0.9877;
    d[7][0]= 0.998;
    d[8][0]= 0.999;*/
     return new DefaultTableModel(d,new String[]{"X"});
}
    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
